stats_weekly_sorted_fields = [
    'date', 'date.to', 'week.hospitalized.vaccinated', 'week.hospitalized.other',
    'week.icu.vaccinated', 'week.icu.vaccinatedpartially', 'week.icu.recovered', 'week.icu.other',
    'week.confirmed', 'week.investigated', 
    'week.healthcare', 'week.healthcare.male', 'week.healthcare.female', 'week.rhoccupant',
    'week.loc.family', 'week.loc.work', 'week.loc.school', 'week.loc.hospital', 'week.loc.otherhc', 'week.loc.rh', 
    'week.loc.prison', 'week.loc.transport', 'week.loc.shop', 'week.loc.restaurant', 'week.loc.sport', 
    'week.loc.gathering_private', 'week.loc.gathering_organized', 'week.loc.other', 'week.loc.unknown',
    'week.sent_to.quarantine', 'week.src.quarantine', 'week.src.import', 'week.src.import-related', 
    'week.src.local', 'week.src.unknown',
    'week.from.aus', 'week.from.aut', 'week.from.aze', 'week.from.bel', 'week.from.bgr', 'week.from.bih', 
    'week.from.cze', 'week.from.mne', 'week.from.dnk', 'week.from.dom', 'week.from.est', 'week.from.fra', 
    'week.from.grc', 'week.from.hrv', 'week.from.irn', 'week.from.ita', 'week.from.kaz', 'week.from.xkx', 
    'week.from.hun', 'week.from.mkd', 'week.from.mlt', 'week.from.mar', 'week.from.fsm', 'week.from.deu', 
    'week.from.pak', 'week.from.pol', 'week.from.rou', 'week.from.rus', 'week.from.svk', 'week.from.srb',
    'week.from.esp', 'week.from.swe', 'week.from.che', 'week.from.tur', 'week.from.ukr', 'week.from.gbr',
    'week.from.usa', 'week.from.are', 'week.from.nld', 'week.from.prt', 'week.from.lva', 'week.from.alb',
    'week.from.cub', 'week.from.mli', 'week.from.egy', 'week.from.tza', 'week.from.fin', 'week.from.nam',
    'week.from.jib', 'week.from.mdv', 'week.from.qat', 'week.from.afg', 'week.from.npl', 'week.from.cyp',
    'week.from.mus', 'week.from.tun', 'week.from.kgz', 'week.from.irl', 'week.from.rwa', 'week.from.zaf',
    'week.from.uzb', 'week.from.bwa', 'week.from.gnq', 'week.from.gmb', 'week.from.ala', 'week.from.lux',
    'week.from.abw', 'week.from.wlf', 'week.from.sur', 'week.from.isr', 'week.from.nor', 'week.from.pyf',
    'week.from.pan', 'week.from.per', 'week.from.zwe', 'week.from.jor', 'week.from.ltu', 'week.from.syc',
    'week.from.ecu', 'week.from.ven', 'week.from.smr', 'week.from.cod', 'week.from.ken', 'week.from.sau',
    'week.from.swz', 'week.from.isl', 'week.from.caf', 'week.from.tha', 'week.from.bra', 'week.from.civ',
    'week.from.col'
]

mapping = {
    ' NEZNANO': 'unknown',
    'Afganistan': 'afg',
    'Alandski otoki': 'ala',
    'Albanija': 'alb',
    'Aruba': 'abw',
    'Avstralija': 'aus',
    'Avstrija': 'aut',
    'Azerbajdžan': 'aze',
    'Belgija': 'bel',
    'Bocvana': 'bwa',
    'Bolgarija': 'bgr',
    'Bosna in Hercegovina': 'bih',
    'Brazilija': 'bra',
    'Ciper': 'cyp',
    'Češka': 'cze',
    'Črna Gora': 'mne',
    'Danska': 'dnk',
    'Demokratična republika Kongo': 'cod',
    'Džibuti': 'jib',
    'Dominikanska republika': 'dom',
    'Egipt': 'egy',
    'Ekvador': 'ecu',
    'Ekvatorialna Gvineja': 'gnq',
    'Estonija': 'est',
    'Finska': 'fin',
    'Francija': 'fra',
    'Francoska Polinezija': 'pyf',
    'Gambija': 'gmb',
    'Grčija': 'grc',
    'Hrvaška': 'hrv',
    'Iran': 'irn',
    'Irska': 'irl',
    'Islandija': 'isl',
    'Italija': 'ita',
    'Izrael': 'isr',
    'Jordanija': 'jor',
    'Južna afrika': 'jar',
    'Katar': 'qat',
    'Kazahstan': 'kaz',
    'Kenija':'ken',
    'Kirgizistan (Kirgizija)': 'kgz',
    'Kolumbija': 'col',
    'Kosovo': 'xkx',
    'Kuba': 'cub',
    'Latvija': 'lva',
    'Litva': 'ltu',
    'Luksemburg': 'lux',
    'Madžarska': 'hum',
    'Makedonija': 'mkd',
    'Maldivi': 'mdv',
    'NAM': 'nam',
    'Namibija': 'nam',
    'Nepal': 'npl',
    'Nizozemska': 'nld',
    'Norveška': 'nor',
    'Mali': 'mli',
    'Malta': 'mlt',
    'Maroko': 'mar',
    'Mauricius (Moris)': 'mus',
    'Mehika': 'mex',
    'Mikronezija': 'fsm',
    'Nemčija': 'deu',
    'Otočje Valis in Futuna': 'wlf',
    'Pakistan': 'pak',
    'Panama': 'pan',
    'Poljska': 'pol',
    'Peru': 'per',
    'Portugalska': 'prt',
    'Romunija': 'rou',
    'Ruanda': 'rwa',
    'Ruska federacija': 'rus',
    'San Marino': 'smr',
    'Savdska Arabija': 'sau',
    'Sejšeli': 'syc',
    'Slonokoščena obala': 'civ',
    'Slovaška': 'svk',
    'Slovenija': 'svn',
    'Srednjeafriška republika': 'caf',
    'Surinam': 'sur',
    'Svazi': 'swz',
    'Španija': 'esp',
    'Srbija': 'srb',
    'Švedska': 'swe',
    'Švica': 'che',
    'Tajska': 'tha',
    'Tanzanija': 'tza',
    'Tunizija': 'tun',
    'Turčija': 'tur',
    'Ukrajina': 'ukr',
    'Uzbekistan': 'uzb',
    'Venezuela': 'ven',
    'Združeno kraljestvo': 'gbr',
    'Združeno kraljestvo Velike Britanije in Severne Irske': 'gbr',
    'Združene države Amerike': 'usa',
    'Združeni Arabski Emirati': 'are',
    'Zimbabve': 'zwe'
}


def get_county_code(country_name: str):
    return mapping[country_name]
