mapping = {
    ' NEZNANO': 'unknown',
    'Afganistan': 'afg',
    'Albanija': 'alb',
    'Avstralija': 'aus',
    'Avstrija': 'aut',
    'Azerbajdžan': 'aze',
    'Belgija': 'bel',
    'Bolgarija': 'bgr',
    'Bosna in Hercegovina': 'bih',
    'Ciper': 'cyp',
    'Češka': 'cze',
    'Črna Gora': 'mne',
    'Danska': 'dnk',
    'Džibuti': 'jib',
    'Dominikanska republika': 'dom',
    'Egipt': 'egy',
    'Estonija': 'est',
    'Finska': 'fin',
    'Francija': 'fra',
    'Grčija': 'grc',
    'Hrvaška': 'hrv',
    'Iran': 'irn',
    'Irska': 'irl',
    'Italija': 'ita',
    'Katar': 'qat',
    'Kazahstan': 'kaz',
    'Kirgizistan (Kirgizija)': 'kgz',
    'Kosovo': 'xkx',
    'Kuba': 'cub',
    'Latvija': 'lva',
    'Madžarska': 'hum',
    'Makedonija': 'mkd',
    'Maldivi': 'mdv',
    'NAM': 'nam',
    'Namibija': 'nam',
    'Nepal': 'npl',
    'Nizozemska': 'nld',
    'Mali': 'mli',
    'Malta': 'mlt',
    'Maroko': 'mar',
    'Mauricius (Moris)': 'mus',
    'Mehika': 'mex',
    'Mikronezija': 'fsm',
    'Nemčija': 'deu',
    'Pakistan': 'pak',
    'Poljska': 'pol',
    'Portugalska': 'prt',
    'Romunija': 'rou',
    'Ruanda': 'rwa',
    'Ruska federacija': 'rus',
    'Slovaška': 'svk',
    'Slovenija': 'svn',
    'Španija': 'esp',
    'Srbija': 'srb',
    'Švedska': 'swe',
    'Švica': 'che',
    'Tanzanija': 'tza',
    'Tunizija': 'tun',
    'Turčija': 'tur',
    'Ukrajina': 'ukr',
    'Združeno kraljestvo': 'gbr',
    'Združeno kraljestvo Velike Britanije in Severne Irske': 'gbr',
    'Združene države Amerike': 'usa',
    'Združeni Arabski Emirati': 'are',
}


def get_county_code(country_name: str):
    return mapping[country_name]
