name = {  # sorted by value
    'Zdravstveni dom Ajdovščina': 'ajdovščina',
    'Zdravstveni dom Bled': 'bled',
    'Zdravstvenim dom Bled': 'bled',
    'Zdravstveni dom Bohinj': 'bohinj',
    'Zdravstveni dom Brežice': 'brežice',
    'Zdravstveni dom Celje (podatki pri SB CE)': 'celje',
    'SB Celje': 'celje_sb',
    'Sb Celje': 'celje_sb',
    'Celje': 'celje_sb',  # TODO it's not clear it's a hospital, this should be handled differently
    'Zdravstveni dom dr. Božidarja Lavriča - Cerknica': 'cerknica',
    'Zdravstveni dom Črnomelj': 'črnomelj',
    'Zdravstveni dom Domžale': 'domžale',
    'Zdravstveni dom Dravograd': 'dravograd',
    'Zdravstveni dom Gornja Radgona': 'gornja_radgona',
    'Zdravstveni dom Grosuplje': 'grosuplje',
    'Zdravstveni dom Hrastnik': 'hrastnik',
    'Zdravstveni dom Idrija': 'idrija',
    'Zdravstveni dom Ilirska Bistrica': 'ilirska_bistrica',
    'Zdravstveni dom Ivančna Gorica': 'ivančna_gorica',
    'Zdravstveni dom Izola': 'izola',
    'Zdravstveni dom Jesenice': 'jesenice',
    'Zdravstveni dom dr. Julija Polca Kamnik': 'kamnik',
    'Zdravstveni dom Kočevje': 'kočevje',
    'Zdravstveni dom Koper (CUS)': 'koper',
    'Zdravstveni dom Kranj': 'kranj',
    'Zdravstveni dom Krško': 'krško',
    'Zdravstveni dom Laško': 'laško',
    'Zdravstveni dom Lenart': 'lenart',
    'Zdravstveni dom Lendava': 'lendava',
    'Zdravstveni dom Litija': 'litija',
    'Zdravstveni dom Ljubljana': 'ljubljana',
    'Zdravstveni dom za študente Univerze v Ljubljani': 'ljubljana_študentski',
    'Zdravstveni dom za študente UL': 'ljubljana_študentski',
    'Zdravstveni dom za študente': 'ljubljana_študentski',
    'SŽ - Železniški zdravstveni dom Ljubljana': 'ljubljana_sž',
    'Zdravstveni dom Ljutomer': 'ljutomer',
    'Zdravstveni dom Logatec': 'logatec',
    'Zdravstveni dom dr. Adolfa Drolca Maribor': 'maribor',
    'Zdravstveni dom Medvode': 'medvode',
    'Zdravstveni dom Metlika': 'metlika',
    'Zdravstveni dom Murska Sobota (VT)': 'murska_sobota',
    'Zgornjesavinjski zdravstveni dom Nazarje': 'nazarje',
    'Zdravstveni dom Osnovno varstvo Nova Gorica': 'nova_gorica',
    'Zdravstveni dom OV Nova Gorica': 'nova_gorica',
    'Zdravstveni dom Nova Gorica': 'nova_gorica',
    'Zdravstveni dom Novo mesto': 'novo_mesto',
    'Zdravstveni dom Novo mesto (podatki pri SB NM)': 'novo_mesto',
    'SB Novo mesto': 'novo_mesto_sb',
    'Novo mesto': 'novo_mesto_sb',  # TODO it's not clear it's a hospital, this should be handled differently
    'Zdravstveni dom Ormož': 'ormož',
    'Zdravstveni dom Piran': 'piran',
    'Zdravstveni dom dr. Franca Ambrožiča Postojna': 'postojna',
    'Zdravstveni dom Ptuj': 'ptuj',
    'Zdravstveni dom Radeče': 'radeče',
    'Zdravstveni dom Radlje ob Dravi': 'radlje_ob_dravi',
    'Zdravstveni dom Radovljica': 'radovljica',
    'Zdravstveni dom Ravne na Koroškem': 'ravne_na_koroškem',
    'Zdravstveni dom dr. Janeza Oražma Ribnica': 'ribnica',
    'Zdravstveni dom Ribnica': 'ribnica',
    'Zdravstveni dom Sevnica': 'sevnica',
    'Zdravstveni dom Sežana': 'sežana',
    'Zdravstveni dom Slovenj Gradec': 'slovenj_gradec',
    'Zdravstveni dom Slovenska Bistrica': 'slovenska_bistrica',
    'Zdravstveni dom Slovenske Konjice': 'slovenske_konjice',
    'Zdravstveni dom Šentjur': 'šentjur',
    'Zdravstveni dom Škofja loka': 'škofja_loka',
    'Zdravstveni dom Šmarje pri Jelšah': 'šmarje_pri_jelšah',
    'Zdravstveni dom Tolmin': 'tolmin',
    'Zdravstveni dom Trbovlje': 'trbovlje',
    'Zdravstveni dom Trbovlje VT': 'trbovlje',
    'Zdravstveni dom Trebnje': 'trebnje',
    'Zdravstveni dom Tržič': 'tržič',
    'Zdravstveni dom Velenje': 'velenje',
    'Zdravstveni dom Vrhnika': 'vrhnika',
    'Zdravstveni dom Zagorje ob Savi': 'zagorje_ob_savi',
    'Zdravstveni dom Zagorje': 'zagorje_ob_savi',
    'ZRCK': 'zrck',
    'Zdravstveni dom dr. Jožeta Potrate Žalec': 'žalec',
}
unique_short_names = []  # preserved sort
for key, value in name.items():
    if value not in unique_short_names:
        unique_short_names.append(value)

region = {
    'ajdovščina': 'ng',
    'bled': 'kr',
    'bohinj': 'kr',
    'brežice': 'kk',
    'celje': 'ce',
    'celje_sb': 'ce',
    'cerknica': 'po',
    'črnomelj': 'nm',
    'domžale': 'lj',
    'dravograd': 'sg',
    'gornja_radgona': 'ms',
    'grosuplje': 'lj',
    'hrastnik': 'za',
    'idrija': 'ng',
    'ilirska_bistrica': 'po',
    'ivančna_gorica': 'lj',
    'izola': 'kp',
    'jesenice': 'kr',
    'kamnik': 'lj',
    'kočevje': 'nm',
    'koper': 'kp',
    'kranj': 'kr',
    'krško': 'kk',
    'laško': 'ce',
    'lenart': 'mb',
    'lendava': 'ms',
    'litija': 'za',
    'ljubljana': 'lj',
    'ljubljana_študentski': 'lj',
    'ljubljana_sž': 'lj',
    'ljutomer': 'ms',
    'logatec': 'lj',
    'maribor': 'mb',
    'medvode': 'lj',
    'metlika': 'nm',
    'murska_sobota': 'ms',
    'nazarje': 'ce',
    'nova_gorica': 'ng',
    'nova_gorica': 'ng',
    'novo_mesto': 'nm',
    'novo_mesto_sb': 'nm',
    'ormož': 'mb',
    'piran': 'kp',
    'postojna': 'po',
    'ptuj': 'mb',
    'radeče': 'kk',
    'radlje_ob_dravi': 'sg',
    'radovljica': 'kr',
    'ravne_na_koroškem': 'sg',
    'ribnica': 'nm',
    'šentjur': 'ce',
    'sevnica': 'kk',
    'sežana': 'kp',
    'škofja_loka': 'kr',
    'slovenj_gradec': 'sg',
    'slovenska_bistrica': 'mb',
    'slovenske_konjice': 'ce',
    'šmarje_pri_jelšah': 'ce',
    'tolmin': 'ng',
    'trbovlje': 'za',
    'trebnje': 'nm',
    'tržič': 'kr',
    'velenje': 'ce',
    'vrhnika': 'lj',
    'zagorje_ob_savi': 'za',
    'žalec': 'ce',
    'zrck': 'sg'
}
