# This is a basic workflow to help you get started with Actions

name: Sewage update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/sewage.yml'
    - 'transform/**.py'
    - 'requirements.txt'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/sewage.yml'
    - 'transform/**.py'
    - 'requirements.txt'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 */1 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v2.1.4
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: "Run sewage update transform/sewage.py"
      run: | 
        python transform/sewage.py 

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la csv/sewage.*
        git status
        git diff

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish NIB Sewage changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'NIB Sewage data update 🤖'
        rebase: 'true' # pull and rebase before commit
        files: csv/sewage.*
        name: Sledilnik data scrape bot 🤖
        email: info@sledilnik.org
