# This is a basic workflow to help you get started with Actions

name: Sewage OPSI data update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/sewage-opsi.yml'
    - 'transform/utils.py'
    - 'update_sewage_opsi.py'
    - 'requirements.txt'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/sewage-opsi.yml'
    - 'transform/utils.py'
    - 'update_sewage_opsi.py'
    - 'requirements.txt'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 12 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: "Run Sewage update update_sewage_opsi.py"
      run: | 
        python update_sewage_opsi.py 

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la csv/sewage-*
        git status
        git diff

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish sewage changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Sewage data update 🤖'
        rebase: 'true' # pull and rebase before commit
        files: sources/opsi/sewage/* csv/sewage-*
        name: Sledilnik data scrape bot 🤖
        email: info@sledilnik.org
